import React from "react";

const History = () => {
  return (
    <div>
      <h1 className="page-title">History</h1>
      <h4 className="page-title">THE OYSTER BAR</h4>
      <div className="history-text">
        <p>
          THE ORIGINAL SALOON FIRST OPENED AT 1830 SOUTH CALHOUN IN THE SUMMER
          OF 1888. THE PROPRIETOR WAS THE HONORABLE FERDINAND OETTING. TWO YEARS
          LATER, IN 1890, A FIREMAN FOR THE PENNSYLVANIA RAILROAD, WT. HARVEY,
          PURCHASED THE SALOON.
        </p>
        <p>
          W.T. HIRED A BARTENDER BY THE NAME OF JOSEPH J. SCHNEE. IN 1894 JOSEPH
          PURCHASED THE SALOON THUS BEGINNING THE LONGEST FAMILY OWNERSHIP OF
          THE ESTABLISHMENT. ROSINA AND JOSEPH LIVED ABOVE THE SALOON UNTIL
          APPROXIMATELY 1910.
        </p>
        <p>
          SHORTLY AFTER JOSEPH PURCHASED THE SALOON PROHIBITION WAS USHERED IN.
          FROM 1918 TO 1927 HE SOLD SOFT DRINKS IN THE FRONT… AS RUMOR HAS IT
          THERE WERE OTHER LIBATIONS AVAILABLE VIA THE BACK DOOR IN THE INFAMOUS
          “BACK ROOM”.
        </p>
        <p>
          THE DEPRESSION, COUPLED WITH PROHIBITION, FORCED JOSEPH TO CLOSE
          BETWEEN THE YEARS OF 1928 AND 1931. IN 1932, THE COUNTRY BEGAN TO
          REBOUND FROM THE DEPRESSION, PROHIBITION WAS ABOLISHED, AND F.D.R.
          CAME INTO POWER. LEO SCHNEE (JOSEPH’S SON) OPENED THE SALOON UNDER THE
          NAME OF HOOSIER PRODUCTS CO, MALT.
        </p>
        <p>
          LEO WAS SAID TO BE A RATHER CANTANKEROUS PROPRIETOR. IF HE LIKED YOU,
          HE SERVED YOU. IF HE DIDN’T, HE DIDN’T.
        </p>
        <p>
          LEO OPERATED THE SALOON UNDER A VARIETY OF NAMES. FROM 1935 TO 1939,
          IT WAS CALLED SCHNEE’S RESTAURANT. FROM 1940 TO 1944, IT WAS KNOWN AS
          SCHNEE’S LIQUORS.
        </p>
        <p>
          FROM 1945 TO 1953, THE SALOON HAD SEVERAL DIFFERENT OWNERS AND NAMES -
          THE MOST NOTABLE BEING “THE WIFFENPOOF” UNDER THE MANAGEMENT OF M.
          MCNAMARA AND R. VENDERLEY.
        </p>
        <p>
          IN 1954, THE REAL OYSTER BAR ERA BEGAN. HUGHIE JOHNSTON, A LOCAL
          SUPERSTAR ATHLETE, PURCHASED THE SALOON AND PROPERTY FROM LEO SCHNEE.
          HUGHIE PLAYED FIRST BASE FOR THE WORLD CHAMPION ZOLLNER PISTONS
          SOFTBALL TEAM. IN 1954, HUGHIE BROUGHT THE TEAM’S STAR SECOND BASEMEN,
          NEAL BARILLE, INTO THE BUSINESS AND OPERATED IT AS HUGHIE’S TAP FROM
          1954 TO 1962. HUGHIE ALSO INTRODUCED OYSTERS IN 1954.
        </p>
        <p>
          DURING THE JOHNSTON AND BARILLE YEARS THE SALOON BECAME A FAVORITE
          HAUNT OF PROSECUTORS, LAWYERS, AND OTHER PROFESSIONALS.
        </p>
        <p>
          IN 1963, NEAL BARILLE PURCHASED HUGHIE’S TAP AND CHANGED THE NAME TO
          “NEAL’S OYSTER BAR”. NEAL OPERATED THE RESTAURANT/SALOON VERY
          SUCCESSFULLY UNTIL 1975. ALAN HUFFMAN AND ALEX LAGUNA THEN PURCHASED
          THE BUSINESS AND SHORTENED THE NAME TO “THE OYSTER BAR”. ALAN
          REMODELED THE KITCHEN, BATHROOMS, AND BAR TO THEIR PRESENT STATE.
        </p>
        <p>
          IN 1987, A NEW ERA BEGAN WHEN STEVEN AND BRENDA GARD PURCHASED THE
          OYSTER BAR. THE OYSTER BAR OPENED THE NEW MILLENNIUM WITH A NEW AND
          EXCITING CONCEPT FEATURING A RAW BAR, MICROBREWERY, AND OUR SAME
          COMMITMENT TO EXCELLENCE OF PRODUCT AND SERVICE.
        </p>
        <p>
          WE HOPE TO USHER IN OUR OWN ERA MAKING THE OYSTER BAR A FAVORITE
          DINING AND DRINKING SALOON. THE OYSTER BAR IS SERIOUS IN ITS
          COMMITMENT TO BRING YOU THE BEST AND HAVE FUN DOING IT.
        </p>
      </div>
    </div>
  );
};

export default History;
